### ISSUE TITLE
`mad app mqtt` not available

### ISSUE THREAD

**Issue by v3470** [synrc/mad#103]
And found it in [commit history](https://github.com/synrc/mad/commit/7cfbfa15bbb7b2f6a198928d58aae6e2e4c90ee1). Is that mean mqtt skeleton is deprecated? Or is there any alternative solution to init n2p mqtt app?

**Comment by 5HT** [comment]
Yes, `mad app mqtt` was abandoned. If you need N2O MQTT app skeleton, please use: 
[1]. https://github.com/synrc/review
[2]. https://review.n2o.dev
