### ISSUE TITLE
Feature request bundle beam emulator

### ISSUE THREAD

**Issue by khia** [synrc/mad#22]
It would be a killer feature if you could bundle beam emulator into bundle. This would allow writing small cli tools for systems where erlang is not installed. [Crate](https://github.com/copiousfreetime/crate/blob/master/data/crate_boot.c) for ruby could be used to get general idea of the feature. In order to avoid modification of erts source you would probably want to [overide entrypoint](http://stackoverflow.com/questions/7494244/how-to-change-the-entry-point-in-gcc) to build static beam emulator which you can link with loader. Magic to start `erl` from C is in `erl_start`/`erl_init` from [erl_init.c](https://github.com/erlang/otp/blob/172e812c491680fbb175f56f7604d4098cdc9de4/erts/emulator/beam/erl_init.c).

**Comment by 5HT** [comment]
There is alredy relx support in mad, relx is able to bundle BEAM virtual machine, runtime and OTP.

**Comment by khia** [comment]
I don't think relx has support for that. It creates a directory structure for a relase but it doesn't produce single executable binary. The idea of the feature is to build static version of beam VM and have small application which can be used as:
```
cat loader > result.app
cat beam.vm >> result.app
cat mad.bundle >> result.app
chmod +x result.app
```
Or loader could include beam if it is easier.
Anyway just an idea.

**Comment by 5HT** [comment]
You can use self-extracting archive.
