### ISSUE TITLE
The example in README.md is not working

### ISSUE THREAD

**Issue by norton** [synrc/mad#23]
The example in README.md is not working.

From Git blame, it appears the commit e8b7d58 for adding kjell support is to blame.

```
$ make
$ mad app "sample"
$ ./mad app "sample"
$ cd sample/
$ ../mad deps compile plan bundle "web_app"
$ ./web_app 
escript: exception error: undefined function mad_repl:main/1
  in function  escript:run/2 (escript.erl, line 752)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1 
  in call from init:start_em/1 
```

I tried with Erlang/OTP 17.4

```
$ erl --version
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.3  (abort with ^G)
1> 
```

**Comment by 5HT** [comment]
Thanks for reporting, fixed in 90c9930305b6974b6c250e635c4508e91617dee8

**Comment by diko4096** [comment]
With the mad binary from ad2decb thing become worser:
`
mad app "sample"
cd sample
mad deps compile plan bundle "web_app"
...
Writing /home/user/sample/apps/n2o_sample/ebin/n2o_sample.app
DTL Compiling /home/user/sample/apps/n2o_sample/priv/templates/index.html
:0: Warning: function render_tag/3 is unused
Plan Params: []
escript: exception error: undefined function mad_plan:main/1
  in function  lists:foreach/2 (lists.erl, line 1336)
  in call from escript:run/2 (escript.erl, line 752)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1 
  in call from init:start_em/1 
`
Erlang:
`
erl --version
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:16:16] [async-threads:10] [hipe] [kernel-poll:false]
`
Mad
`
mad 
VXZ MAD Build Tool version 1.1

sha1sum mad
08c417f45fe8507d06c26b7f5771268dc50aa654  mad
`

**Comment by 5HT** [comment]
Are you sure?

https://gist.github.com/5HT/9d1c85ea6873d1533ac8
