### ISSUE TITLE
In the README.md, the example for building OTP Release needs clarification.

### ISSUE THREAD

**Issue by norton** [synrc/mad#24]
In the README.md file, there are a few clarifications that would be helpful.

The mad release command requires relx to be in one's $PATH.

The command to invoke the console appears to be:

```
$ _rel/sample/bin/sample console
```

As an aside, how to check if the sample application and release is working properly?

Thanks.

**Comment by 5HT** [comment]
I guess this answer should be asked to OTP or relx.
