### ISSUE TITLE
mad doesn't seem to handle behaviors properly

### ISSUE THREAD

**Issue by rgrinberg** [synrc/mad#33]
For example, consider the following repository: https://github.com/basho/riak-erlang-client

`$ mad deps compile` will give

```
~/riak-erlang-client/src/riakc_flag.erl:32: behaviour riakc_datatype undefined
```

Anyway to fix this?

**Comment by 5HT** [comment]
mad doesn't support rebar plugins and never will.

**Comment by rgrinberg** [comment]
Could you describe the problem for me in a little bit more detail? Which plugin you're talking about for example.

The real problem is that I'm trying to use `riak-erlang-client` as a dependency and that doesn't work.

**Comment by 5HT** [comment]
1. https://github.com/basho/riak-erlang-client/blob/master/rebar.config#L7
2. https://github.com/basho/riak_pb/blob/develop/rebar.config#L12
3. https://github.com/basho/riak_pb/blob/develop/plugins/riak_pb_msgcodegen.erl#L28
