### ISSUE TITLE
mad fails to get dependencies in windows

### ISSUE THREAD

**Issue by vjorjo** [synrc/mad#45]
D:\AppsDev\Erlang\n2o\myapps>mad deps
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
escript: exception error: enoent
  in function  open_port/2
     called as open_port({spawn_executable,"/bin/sh"},
                         [stream,stderr_to_stdout,binary,exit_status,
                          {args,["-c",
                                 "git clone git://github.com/evanmiller/erlydtl deps/erlydtl && cd deps/erlydtl && git checkout \"0.8.0\""]},
                          {cd,"."},
                          {env,[]}])
  in call from sh:run/5 (/Users/5HT/depot/synrc/mad/deps/sh/src/sh.erl, line 42)
  in call from mad_git:fetch_dep/8 (/Users/5HT/depot/synrc/mad/src/sources/mad_git.erl, line 58)
  in call from mad_git:fetch/4 (/Users/5HT/depot/synrc/mad/src/sources/mad_git.erl, line 26)
  in call from mad:'-main/1-fun-3-'/3 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 19)
  in call from lists:foldl/3 (lists.erl, line 1262)
  in call from mad:main/1 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 18)

**Comment by 5HT** [comment]
just provide an access to a file "/bin/sh"

**Comment by vjorjo** [comment]
but there is no such file in windows

**Comment by 5HT** [comment]
make with `cp`

**Comment by vjorjo** [comment]
In and msys2 shell, in the beginning, I got these error results:
----------------->>>>>
ga@ga-PC MSYS /d/AppsDev/Erlang/n2o/myapps
$ mad deps
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
escript: exception error: enoent
  in function  open_port/2
     called as open_port({spawn_executable,"/bin/sh"},
                         [stream,stderr_to_stdout,binary,exit_status,
                          {args,["-c",
                                 "git clone git://github.com/evanmiller/erlydtl                 deps/erlydtl && cd deps/erlydtl && git checkout \"0.8.0\""]},
                          {cd,"."},
                          {env,[]}])
  in call from sh:run/5 (/Users/5HT/depot/synrc/mad/deps/sh/src/sh.erl, line 42)
  in call from mad_git:fetch_dep/8 (/Users/5HT/depot/synrc/mad/src/sources/mad_g                it.erl, line 58)
  in call from mad_git:fetch/4 (/Users/5HT/depot/synrc/mad/src/sources/mad_git.e                rl, line 26)
  in call from mad:'-main/1-fun-3-'/3 (/Users/5HT/depot/synrc/mad/src/mad.erl, l                ine 19)
  in call from lists:foldl/3 (lists.erl, line 1262)
  in call from mad:main/1 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 18)
<<<<---------------------------------
Then, I created a folder D:\bin as a hardlink to where msys2/usr/bin  was ( in my PC it was in E:\msys64\usr\bin ) and this solved the problem and led to successfully get the dependencies:
----------------->>>>
ga@ga-PC MSYS /d/AppsDev/Erlang/n2o/myapps
$ mad deps
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
==> dependency: "git://github.com/extend/cowboy" tag: {tag,"1.0.1"}
==> dependency: "git://github.com/ninenines/cowlib.git" tag: "1.0.0"
==> dependency: "git://github.com/ninenines/ranch.git" tag: "1.0.0"
==> dependency: "git://github.com/uwiger/gproc.git" tag: {tag,"0.3"}
==> dependency: "git://github.com/synrc/fs" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/sh" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/mad" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/active" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/nitro" tag: {tag,"0.9"}
==> dependency: "git://github.com/synrc/n2o" tag: {tag,"2.9"}
==> dependency: "git://github.com/sile/jsone.git" tag: {tag,"v0.3.3"}
==> dependency: "git://github.com/rustyio/sync.git" tag: {branch,"master"}

**Comment by 5HT** [comment]
Closed by https://github.com/synrc/sh/commit/8bff94e67aba9a6583a820a5a8b314c8dac7af48
