### ISSUE TITLE
mad fails to sync code on the fly in windows

### ISSUE THREAD

**Issue by vjorjo** [synrc/mad#46]
While it seems that when a source file is modified, mad is sensing it and is doing the compilation:

1> ==> "sample"
1> ==> "d:/AppsDev/Erlang/n2o/myapps"
1> ==> "d:/AppsDev/Erlang/n2o/myapps/apps"
1> ==> "d:/AppsDev/Erlang/n2o/myapps/apps/sample"
1> Compiling d/apps/sample/src/index.erl
1> ==> "sample"
1> ==> "d:/AppsDev/Erlang/n2o/myapps"
1> ==> "d:/AppsDev/Erlang/n2o/myapps/apps"
1> ==> "d:/AppsDev/Erlang/n2o/myapps/apps/sample"
1>

it actually doesn't load the new changed code. For example, if you have a page, say index and you change anything in index.erl ( e.g. some text in the body of a button in fun/0 body() ) and you press refresh (F5) in the browser you still get the old page.
The only solution in order to get the new page is to press Ctrl+C for repl termination and run "mad plan repl" again.

**Comment by 5HT** [comment]
Opened in `active`: https://github.com/synrc/active/issues/7
