### ISSUE TITLE
Repl in mad in windows doesn't accept any input apart from Ctrl+C.

### ISSUE THREAD

**Issue by vjorjo** [synrc/mad#47]
I tried to run mad in windows with many combinations of its commands and I have never been able to write any erlang term in its repl prompt. It only shows various outputs but never accepts any input from the keyboard unless you press Ctrl+C which terminates mad repl.

Another relative thing is that default backend logger "n2o_log" doesn't work in windows (doesn't log out anything). However, "n2o_io" works just fine, so maybe this is not an issue.

**Comment by 5HT** [comment]
Maybe we should place NOTE in readme about Windows specific behavior

**Comment by vjorjo** [comment]
Maybe, however it would be better if you could fix it, because in your book says in many places to try some erlang commands, e.g.
> wf:config(n2o,protocols).
but currently this is not possible from mad in windows.

**Comment by 5HT** [comment]
OK, I will take a look this week, just need to find Windows machine.

**Comment by carlosedp** [comment]
We had a similar problem on rebar3 where the shell never accepted input on Windows.
Maybe the pull request https://github.com/rebar/rebar3/pull/995 could help.
