### ISSUE TITLE
mad doesn't fail when compilation fails

### ISSUE THREAD

**Issue by proger** [synrc/mad#8]
currently `mad` simply logs all errors mixed with warnings and exists with `0`

**Comment by 5HT** [comment]
`mad plan` and `mad up` commands both now support return codes.
`mad compile` and other commands will come later.

**Comment by proger** [comment]
:+1

**Comment by 5HT** [comment]
ok. from now on mad seems to support monadic error checking on following command: `up`, `compile`, `deps`, `bundle`, `app`, `lib`, `clean`. Trust me it works :-) I'm closing this issue.
