### ISSUE TITLE
mad disregards global configuration

### ISSUE THREAD

**Issue by proger** [synrc/mad#9]
options from top-level `rebar.config` are ignored when traversing dependencies

e.g.:
```erlang
{sub_dirs, ["apps/lib", "apps/tsung", "apps/tsung_controller", "apps/tsung_recorder"]}.
{erl_opts, [{i, "include"}]}.
```
(playground: https://github.com/proger/tsung/tree/madtsung)

**Comment by 5HT** [comment]
tsung is not even rebar compatible.
