### ISSUE TITLE
Discover applications in lib_dirs

### ISSUE THREAD

**Issue by xafizoff** [synrc/mad#91]
I have all applications my project depends on, in `apps` directory. So I keep all libs in freeze. I have to specify in `rebar.config` every single sub dir to get it working:
```erlang
{lib_dirs,["apps"]}.
{sub_dirs,["apps/cowlib","apps/cowboy","apps/ranch","apps/gproc","apps/kvs","apps/jsone","apps/nitro","apps/gen_smtp","apps/n2o",
  "apps/sh","apps/mad","apps/fs","apps/active", "apps/svg"]}.
```
Can this be avoided?

**Comment by proger** [comment]
Is it possible to rename apps to deps? Or set `deps_dir` instead?

**Comment by xafizoff** [comment]
Yes

**Comment by proger** [comment]
Awesome!
